# BACKGROUND
background {
    monitor = DP-2
    path = screenshot
    path = ~/Pictures/backgrounds/icelandic_mountains.jpg
    blur_passes = 4
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.5
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(4e4e4e11)
    inner_color = rgba(28282833)
    font_color = rgb(dfe4f7)
    fade_on_empty = false
    rounding = -1
    check_color = rgb(204, 136, 34)
    font_family = 'Noto Sans'
    placeholder_text = <i><span foreground="##dfe4f7">Input Password...</span></i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgb(dfe4f7)
  font_size = 22
  font_family = 'Noto Sans'
  position = 0, 200
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%-H:%M")"
  color = rgb(dfe4f7)
  font_size = 95
  font_family = 'Noto Sans'
  position = 0, 100
  halign = center
  valign = center
}

