#!/bin/sh

# Define power options
options="  Shutdown\n  Reboot "

# Display options with Rofi and capture choice
choice=$(echo -e "$options" | rofi -theme-str '@import "powermenu"' -dmenu)

# Execute action based on choice
case "$choice" in
    "  Shutdown")
        systemctl poweroff
        ;;
    "  Reboot ")
        systemctl reboot
        ;;
    *)
        exit 1
        ;;
esac
